name: routine
description: "routine project"

publish_to: 'bazar'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.1
  android_alarm_manager_plus: ^3.0.4
  flutter_local_notifications: ^17.0.0
  numberpicker: ^2.1.2
  shamsi_date: ^1.0.2
  url_launcher: ^6.2.5
  package_info_plus: ^5.0.1
  fluttertoast: ^8.2.4


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/png/
    - assets/fonts/

  fonts:
    - family: vazir
      fonts:
        - asset: assets/fonts/vazir_medium.ttf
